# Generated by Django 5.0.4 on 2024-05-15 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finca.finca')),
            ],
        ),
    ]
