# Generated by Django 5.0.4 on 2024-05-15 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('versiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_Datos', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=21)),
                ('formato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='versiones.versione')),
            ],
        ),
    ]
