# Generated by Django 5.0.4 on 2024-05-15 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muestra', '0001_initial'),
        ('versiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muestra.muestra')),
                ('versiones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='versiones.versione')),
            ],
        ),
    ]
