# Generated by Django 5.0.4 on 2024-05-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_documento',
            field=models.BigIntegerField(null=True),
        ),
    ]
